// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace EventRegistrationWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label labelEvent;
		
		protected System.Web.UI.WebControls.DropDownList dropDownListEvents;
		
		protected System.Web.UI.WebControls.Label labelFirstName;
		
		protected System.Web.UI.WebControls.TextBox textFirstName;
		
		protected System.Web.UI.WebControls.Label labelLastName;
		
		protected System.Web.UI.WebControls.TextBox textLastName;
		
		protected System.Web.UI.WebControls.Label labelEmail;
		
		protected System.Web.UI.WebControls.TextBox textEmail;
		
		protected System.Web.UI.WebControls.Button buttonSubmit;
	}
}
